#!/usr/bin/env bash
set -euo pipefail

REPO="${GH_REPO:-JohnBetaCode/rtsp_cam_server}"

require_gh_auth() {
  if ! command -v gh >/dev/null 2>&1; then
    echo "GitHub CLI is not installed or is not on PATH." >&2
    exit 1
  fi

  if ! gh auth status -h github.com >/dev/null 2>&1; then
    echo "GitHub CLI is not authenticated for github.com." >&2
    echo "Run: gh auth login -h github.com" >&2
    exit 1
  fi
}

branch_exists() {
  gh api "repos/${REPO}/branches/$1" >/dev/null 2>&1
}

upsert_label() {
  local name="$1"
  local color="$2"
  local description="$3"

  gh label create "$name" \
    --repo "$REPO" \
    --color "$color" \
    --description "$description" \
    --force >/dev/null
}

configure_repo_settings() {
  gh api "repos/${REPO}" \
    --method PATCH \
    --header "Accept: application/vnd.github+json" \
    --field delete_branch_on_merge=true \
    --field allow_merge_commit=false \
    --field allow_squash_merge=true \
    --field allow_rebase_merge=true >/dev/null
}

protect_main() {
  gh api "repos/${REPO}/branches/main/protection" \
    --method PUT \
    --header "Accept: application/vnd.github+json" \
    --field required_status_checks=null \
    --field enforce_admins=true \
    --field 'required_pull_request_reviews[required_approving_review_count]=1' \
    --field 'required_pull_request_reviews[dismiss_stale_reviews]=true' \
    --field 'required_pull_request_reviews[require_code_owner_reviews]=false' \
    --field restrictions=null \
    --field allow_force_pushes=false \
    --field allow_deletions=false \
    --field required_linear_history=true >/dev/null
}

protect_staging() {
  gh api "repos/${REPO}/branches/staging/protection" \
    --method PUT \
    --header "Accept: application/vnd.github+json" \
    --field required_status_checks=null \
    --field enforce_admins=false \
    --field 'required_pull_request_reviews[required_approving_review_count]=1' \
    --field 'required_pull_request_reviews[dismiss_stale_reviews]=true' \
    --field 'required_pull_request_reviews[require_code_owner_reviews]=false' \
    --field restrictions=null \
    --field allow_force_pushes=false \
    --field allow_deletions=false \
    --field required_linear_history=false >/dev/null
}

protect_develop() {
  gh api "repos/${REPO}/branches/develop/protection" \
    --method PUT \
    --header "Accept: application/vnd.github+json" \
    --field required_status_checks=null \
    --field enforce_admins=false \
    --field required_pull_request_reviews=null \
    --field restrictions=null \
    --field allow_force_pushes=false \
    --field allow_deletions=false \
    --field required_linear_history=false >/dev/null
}

configure_labels() {
  upsert_label "type_bug" "d73a4a" "Bug or unexpected behavior"
  upsert_label "type_feature" "a2eeef" "New feature"
  upsert_label "type_enhancement" "84b6eb" "Improvement to existing behavior"
  upsert_label "type_hotfix" "b60205" "Urgent fix for deployed environments"
  upsert_label "type_release" "5319e7" "Release work"
  upsert_label "type_chore" "cfd3d7" "Maintenance or cleanup"
  upsert_label "type_docs" "0075ca" "Documentation"

  upsert_label "PRIORITY_LOW" "0e8a16" "Low priority"
  upsert_label "PRIORITY_MEDIUM" "fbca04" "Medium priority"
  upsert_label "PRIORITY_HIGH" "d93f0b" "High priority"
  upsert_label "PRIORITY_SATANIC" "000000" "Critical blocker"

  upsert_label "state_in_progress" "1d76db" "Work is in progress"
  upsert_label "state_tech_check" "5319e7" "Needs technical review"
  upsert_label "state_qa_check" "006b75" "Needs QA review"
  upsert_label "state_ready_to_test" "0e8a16" "Ready to test"
  upsert_label "state_testing" "fbca04" "Testing in progress"

  upsert_label "sys_streaming" "0052cc" "MediaMTX, RTSP, WebRTC, HLS, cameras"
  upsert_label "sys_api" "1d76db" "FastAPI control plane or API work"
  upsert_label "sys_config" "c2e0c6" "Configuration, environment, or deployment files"
  upsert_label "sys_docs" "0075ca" "Documentation system"
  upsert_label "sys_cicd" "5319e7" "CI/CD and GitHub automation"
  upsert_label "sys_other" "ededed" "Other subsystem"

  upsert_label "automerge" "0e8a16" "Eligible for automatic merge"
  upsert_label "automergesquash" "0e8a16" "Use squash when automerging"
  upsert_label "auto_generated" "cfd3d7" "Generated by automation"
  upsert_label "hold_on" "d93f0b" "Do not merge yet"
}

main() {
  require_gh_auth

  echo "Configuring repository settings for ${REPO}..."
  configure_repo_settings

  echo "Creating or updating labels..."
  configure_labels

  if branch_exists main; then
    echo "Protecting main..."
    protect_main
  else
    echo "Skipping main protection: branch does not exist."
  fi

  if branch_exists staging; then
    echo "Protecting staging..."
    protect_staging
  else
    echo "Skipping staging protection: branch does not exist."
  fi

  if branch_exists develop; then
    echo "Protecting develop..."
    protect_develop
  else
    echo "Skipping develop protection: branch does not exist."
  fi

  echo "GitHub repository settings are configured."
}

main "$@"
